name: PlatinumCore
version: 1.0
author: Ariel01
description: Helpful Toolbox for pmc moderators
main: mc.platinum.com.PMC
commands:
  pmc:
    description: Base Command
    usage: /<command>
  switcher:
    description: Switcher Ball
    usage: /<command>
  flashtest:
    description: Test command
    usage: /<command>